// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.0
// source: gno/event.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import Long from 'long';

export const protobufPackage = 'gno.bank';

export interface Event {
  type: string;
  attrs: EventAttribute[];
  pkg_path: string;
}

export interface EventAttribute {
  key: string;
  value: string;
}

/** StorageDepositEvent is emitted when a storage deposit fee is locked. */
export interface StorageDepositEvent {
  bytes_delta: Long;
  fee_delta: string;
  pkg_path: string;
}

/** StorageUnlockEvent is emitted when a storage deposit fee is unlocked. */
export interface StorageUnlockEvent {
  bytes_delta: Long;
  fee_refund: string;
  pkg_path: string;
  refund_withheld: boolean;
}

function createBaseEvent(): Event {
  return { type: '', attrs: [], pkg_path: '' };
}

export const Event: MessageFns<Event> = {
  encode(message: Event, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== '') {
      writer.uint32(10).string(message.type);
    }
    for (const v of message.attrs) {
      EventAttribute.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.pkg_path !== '') {
      writer.uint32(26).string(message.pkg_path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Event {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attrs.push(EventAttribute.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Event {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : '',
      attrs: globalThis.Array.isArray(object?.attrs) ? object.attrs.map((e: any) => EventAttribute.fromJSON(e)) : [],
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
    };
  },

  toJSON(message: Event): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = message.type;
    }
    if (message.attrs?.length) {
      obj.attrs = message.attrs.map((e) => EventAttribute.toJSON(e));
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Event>, I>>(base?: I): Event {
    return Event.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Event>, I>>(object: I): Event {
    const message = createBaseEvent();
    message.type = object.type ?? '';
    message.attrs = object.attrs?.map((e) => EventAttribute.fromPartial(e)) || [];
    message.pkg_path = object.pkg_path ?? '';
    return message;
  },
};

function createBaseEventAttribute(): EventAttribute {
  return { key: '', value: '' };
}

export const EventAttribute: MessageFns<EventAttribute> = {
  encode(message: EventAttribute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== '') {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventAttribute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventAttribute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventAttribute {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
    };
  },

  toJSON(message: EventAttribute): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventAttribute>, I>>(base?: I): EventAttribute {
    return EventAttribute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventAttribute>, I>>(object: I): EventAttribute {
    const message = createBaseEventAttribute();
    message.key = object.key ?? '';
    message.value = object.value ?? '';
    return message;
  },
};

function createBaseStorageDepositEvent(): StorageDepositEvent {
  return { bytes_delta: Long.ZERO, fee_delta: '', pkg_path: '' };
}

export const StorageDepositEvent: MessageFns<StorageDepositEvent> = {
  encode(message: StorageDepositEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.bytes_delta.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.bytes_delta.toString());
    }
    if (message.fee_delta !== '') {
      writer.uint32(18).string(message.fee_delta);
    }
    if (message.pkg_path !== '') {
      writer.uint32(26).string(message.pkg_path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDepositEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDepositEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bytes_delta = Long.fromString(reader.int64().toString());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fee_delta = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDepositEvent {
    return {
      bytes_delta: isSet(object.bytes_delta) ? Long.fromValue(object.bytes_delta) : Long.ZERO,
      fee_delta: isSet(object.fee_delta) ? globalThis.String(object.fee_delta) : '',
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
    };
  },

  toJSON(message: StorageDepositEvent): unknown {
    const obj: any = {};
    if (message.bytes_delta !== undefined) {
      obj.bytes_delta = (message.bytes_delta || Long.ZERO).toString();
    }
    if (message.fee_delta !== undefined) {
      obj.fee_delta = message.fee_delta;
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDepositEvent>, I>>(base?: I): StorageDepositEvent {
    return StorageDepositEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDepositEvent>, I>>(object: I): StorageDepositEvent {
    const message = createBaseStorageDepositEvent();
    message.bytes_delta =
      object.bytes_delta !== undefined && object.bytes_delta !== null ? Long.fromValue(object.bytes_delta) : Long.ZERO;
    message.fee_delta = object.fee_delta ?? '';
    message.pkg_path = object.pkg_path ?? '';
    return message;
  },
};

function createBaseStorageUnlockEvent(): StorageUnlockEvent {
  return {
    bytes_delta: Long.ZERO,
    fee_refund: '',
    pkg_path: '',
    refund_withheld: false,
  };
}

export const StorageUnlockEvent: MessageFns<StorageUnlockEvent> = {
  encode(message: StorageUnlockEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.bytes_delta.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.bytes_delta.toString());
    }
    if (message.fee_refund !== '') {
      writer.uint32(18).string(message.fee_refund);
    }
    if (message.pkg_path !== '') {
      writer.uint32(26).string(message.pkg_path);
    }
    if (message.refund_withheld !== false) {
      writer.uint32(32).bool(message.refund_withheld);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageUnlockEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageUnlockEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bytes_delta = Long.fromString(reader.int64().toString());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fee_refund = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.refund_withheld = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageUnlockEvent {
    return {
      bytes_delta: isSet(object.bytes_delta) ? Long.fromValue(object.bytes_delta) : Long.ZERO,
      fee_refund: isSet(object.fee_refund) ? globalThis.String(object.fee_refund) : '',
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
      refund_withheld: isSet(object.refund_withheld) ? globalThis.Boolean(object.refund_withheld) : false,
    };
  },

  toJSON(message: StorageUnlockEvent): unknown {
    const obj: any = {};
    if (message.bytes_delta !== undefined) {
      obj.bytes_delta = (message.bytes_delta || Long.ZERO).toString();
    }
    if (message.fee_refund !== undefined) {
      obj.fee_refund = message.fee_refund;
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    if (message.refund_withheld !== undefined) {
      obj.refund_withheld = message.refund_withheld;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageUnlockEvent>, I>>(base?: I): StorageUnlockEvent {
    return StorageUnlockEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageUnlockEvent>, I>>(object: I): StorageUnlockEvent {
    const message = createBaseStorageUnlockEvent();
    message.bytes_delta =
      object.bytes_delta !== undefined && object.bytes_delta !== null ? Long.fromValue(object.bytes_delta) : Long.ZERO;
    message.fee_refund = object.fee_refund ?? '';
    message.pkg_path = object.pkg_path ?? '';
    message.refund_withheld = object.refund_withheld ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
