// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.0
// source: gno/event.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import Long from 'long';

export const protobufPackage = 'gno.event';

/** GnoEvent is the event type for the bank module */
export interface GnoEvent {
  type: string;
  attributes: GnoEventAttribute[];
  pkg_path: string;
}

/** GnoEventAttribute is the attribute type for the bank module */
export interface GnoEventAttribute {
  key: string;
  value: string;
}

/** StorageDepositEvent is emitted when a storage deposit fee is locked. */
export interface StorageDepositEvent {
  bytes_delta: Long;
  fee_delta: string;
  pkg_path: string;
}

/** StorageUnlockEvent is emitted when a storage deposit fee is unlocked. */
export interface StorageUnlockEvent {
  /** For unlock, BytesDelta is negative */
  bytes_delta: Long;
  fee_refund: string;
  pkg_path: string;
}

function createBaseGnoEvent(): GnoEvent {
  return { type: '', attributes: [], pkg_path: '' };
}

export const GnoEvent: MessageFns<GnoEvent> = {
  encode(message: GnoEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== '') {
      writer.uint32(10).string(message.type);
    }
    for (const v of message.attributes) {
      GnoEventAttribute.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.pkg_path !== '') {
      writer.uint32(26).string(message.pkg_path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GnoEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGnoEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attributes.push(GnoEventAttribute.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GnoEvent {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : '',
      attributes: globalThis.Array.isArray(object?.attributes)
        ? object.attributes.map((e: any) => GnoEventAttribute.fromJSON(e))
        : [],
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
    };
  },

  toJSON(message: GnoEvent): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = message.type;
    }
    if (message.attributes?.length) {
      obj.attributes = message.attributes.map((e) => GnoEventAttribute.toJSON(e));
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GnoEvent>, I>>(base?: I): GnoEvent {
    return GnoEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GnoEvent>, I>>(object: I): GnoEvent {
    const message = createBaseGnoEvent();
    message.type = object.type ?? '';
    message.attributes = object.attributes?.map((e) => GnoEventAttribute.fromPartial(e)) || [];
    message.pkg_path = object.pkg_path ?? '';
    return message;
  },
};

function createBaseGnoEventAttribute(): GnoEventAttribute {
  return { key: '', value: '' };
}

export const GnoEventAttribute: MessageFns<GnoEventAttribute> = {
  encode(message: GnoEventAttribute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== '') {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GnoEventAttribute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGnoEventAttribute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GnoEventAttribute {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
    };
  },

  toJSON(message: GnoEventAttribute): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GnoEventAttribute>, I>>(base?: I): GnoEventAttribute {
    return GnoEventAttribute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GnoEventAttribute>, I>>(object: I): GnoEventAttribute {
    const message = createBaseGnoEventAttribute();
    message.key = object.key ?? '';
    message.value = object.value ?? '';
    return message;
  },
};

function createBaseStorageDepositEvent(): StorageDepositEvent {
  return { bytes_delta: Long.ZERO, fee_delta: '', pkg_path: '' };
}

export const StorageDepositEvent: MessageFns<StorageDepositEvent> = {
  encode(message: StorageDepositEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.bytes_delta.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.bytes_delta.toString());
    }
    if (message.fee_delta !== '') {
      writer.uint32(18).string(message.fee_delta);
    }
    if (message.pkg_path !== '') {
      writer.uint32(26).string(message.pkg_path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDepositEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDepositEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bytes_delta = Long.fromString(reader.int64().toString());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fee_delta = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDepositEvent {
    return {
      bytes_delta: isSet(object.bytes_delta) ? Long.fromValue(object.bytes_delta) : Long.ZERO,
      fee_delta: isSet(object.fee_delta) ? globalThis.String(object.fee_delta) : '',
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
    };
  },

  toJSON(message: StorageDepositEvent): unknown {
    const obj: any = {};
    if (message.bytes_delta !== undefined) {
      obj.bytes_delta = (message.bytes_delta || Long.ZERO).toString();
    }
    if (message.fee_delta !== undefined) {
      obj.fee_delta = message.fee_delta;
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDepositEvent>, I>>(base?: I): StorageDepositEvent {
    return StorageDepositEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDepositEvent>, I>>(object: I): StorageDepositEvent {
    const message = createBaseStorageDepositEvent();
    message.bytes_delta =
      object.bytes_delta !== undefined && object.bytes_delta !== null ? Long.fromValue(object.bytes_delta) : Long.ZERO;
    message.fee_delta = object.fee_delta ?? '';
    message.pkg_path = object.pkg_path ?? '';
    return message;
  },
};

function createBaseStorageUnlockEvent(): StorageUnlockEvent {
  return { bytes_delta: Long.ZERO, fee_refund: '', pkg_path: '' };
}

export const StorageUnlockEvent: MessageFns<StorageUnlockEvent> = {
  encode(message: StorageUnlockEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.bytes_delta.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.bytes_delta.toString());
    }
    if (message.fee_refund !== '') {
      writer.uint32(18).string(message.fee_refund);
    }
    if (message.pkg_path !== '') {
      writer.uint32(26).string(message.pkg_path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageUnlockEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageUnlockEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bytes_delta = Long.fromString(reader.int64().toString());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fee_refund = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pkg_path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageUnlockEvent {
    return {
      bytes_delta: isSet(object.bytes_delta) ? Long.fromValue(object.bytes_delta) : Long.ZERO,
      fee_refund: isSet(object.fee_refund) ? globalThis.String(object.fee_refund) : '',
      pkg_path: isSet(object.pkg_path) ? globalThis.String(object.pkg_path) : '',
    };
  },

  toJSON(message: StorageUnlockEvent): unknown {
    const obj: any = {};
    if (message.bytes_delta !== undefined) {
      obj.bytes_delta = (message.bytes_delta || Long.ZERO).toString();
    }
    if (message.fee_refund !== undefined) {
      obj.fee_refund = message.fee_refund;
    }
    if (message.pkg_path !== undefined) {
      obj.pkg_path = message.pkg_path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageUnlockEvent>, I>>(base?: I): StorageUnlockEvent {
    return StorageUnlockEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageUnlockEvent>, I>>(object: I): StorageUnlockEvent {
    const message = createBaseStorageUnlockEvent();
    message.bytes_delta =
      object.bytes_delta !== undefined && object.bytes_delta !== null ? Long.fromValue(object.bytes_delta) : Long.ZERO;
    message.fee_refund = object.fee_refund ?? '';
    message.pkg_path = object.pkg_path ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
